### ISSUE TITLE
Questions should be displayed by the ordering of question title.

### ISSUE THREAD

**Issue by joker78980** [JennieHo-HPE/Sapporo#25]
Questions should be displayed by the ordering of question title.

![image](https://user-images.githubusercontent.com/43881241/146163271-0ea20fec-b30e-4824-b3ff-ccf1ca34d26a.png)

**Comment by joker78980** [comment]
The ordering is still not correct. 
![image](https://user-images.githubusercontent.com/43881241/146498613-4e98a230-420e-46fd-998d-74295db7d4f8.png)

**Comment by yilanhung** [comment]
> The ordering is still not correct. 

Yes, it's correct. The list was sorted by "title" first, which is of text type, so it induced string comparison, char by char. That's why Q**1**1 comes before Q**2**.

Name your titles to be starting like Q00, Q01, Q02...Q11, or (cleaner) ..., or 00, 01, 02, ... 11, 12...

If you're talking about a specific case, like the one here, "number"s has to be extracted from the "string"s for sorting, I wouldn't hard-code it because specific cases can be many.

For this system, a more reasonable design is allow an admin/author to determine what ordering he/she wants for displaying the problems on an admin UI (remember SharePoint menu editing?), which would be another new feature.

**Comment by yilanhung** [comment]
0855e9c37e351d260aaa1e43fec2a9b95aaa1b8d
